### ISSUE TITLE
Format of GPPT data to split questions and answers

### ISSUE THREAD

**Issue by ruthjohnson78** [NHS-South-Central-and-West/CAP#7]
### Problem
The question and answers in the data are in the same column, they need splitting out so that there is not loads of text on the graphs.

### Proposed Solution
Split the columns into question, answer and summary question flag columns

### Alternatives
1. Do it in SQL instead!
2. Sulk and get Paul to do it.

### Additional Context
N/A

**Comment by Paulj1989** [comment]
Deleted the original branch you created for this because the changes I was making elsewhere were likely to cause some conflicts. Figured it was easier to delete it and then create a fresh branch that is up-to-date, to reduce the risk of potential issues created by conflicts.

**Comment by ruthjohnson78** [comment]
Finished adjustments
